/********************************************************************************
 * Copyright (c) 2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

/*!
up-rust is the Rust language library for
[Eclipse uProtocol&trade;](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/README.adoc) —
a protocol that lets software components (in vehicles and beyond) publish data,
subscribe to it, and call each other's services over whatever messaging
technology a deployment happens to use: MQTT, Zenoh, DDS, shared memory, and
more.

The idea in one sentence: **you write against one small messaging API, and the
technology underneath stays swappable.**

## Your first message

```rust
use up_rust::{PayloadEncoding, UMessageBuilder, UTransport, UUri};

async fn publish_engine_temp(
    transport: &dyn UTransport,
) -> Result<(), Box<dyn std::error::Error>> {
    // Every message has a source address: authority / entity / version / resource.
    let topic = UUri::try_from_parts("my-vehicle", 0x1_0001, 1, 0x8001)?;

    let message = UMessageBuilder::publish(topic)
        .build_with_payload("92.5", PayloadEncoding::TEXT)?;

    transport.send(message).await?;
    Ok(())
}
```

That is the whole application-side model: build a [`UMessage`], hand it to a
[`UTransport`] someone has configured, done. Receiving is the mirror image —
register a [`UListener`] for the addresses you care about.

## Which reader are you?

| You want to... | Start at | Cargo features |
| --- | --- | --- |
| Write an application using publish, subscribe, notifications, or RPC | The role traits in [`communication`], then the [Communication Layer guide](crate::guide::applications::communication) | `communication`, `util` |
| Build and receive messages directly with the smallest API surface | The [Transport Layer application guide](crate::guide::applications::transport) | none |
| Connect a messaging technology to uProtocol | [`UTransport`], then the [transport implementation guide](crate::guide::utransport) | `util` for the runnable guide |

The [`guide`] walks each path end to end with code.

## Three terms you'll meet everywhere

* **uEntity** — any software component that talks uProtocol (an app, a service,
  or a sensor feed).
* **Transport Layer (up-L1)** — the layer that moves messages; a *transport* is
  one implementation of it (Zenoh, MQTT, DDS, and so on).
* **Communication Layer (up-L2)** — the application-facing publish, subscribe,
  notification, and RPC roles built on top of any transport.

## Module map

* [`communication`] contains the up-L2 roles most applications use.
* [`UMessage`], [`UUri`], and [`UAttributes`] form the core message model.
* [`UTransport`] is the up-L1 contract implemented by transport providers.
* [`guide`] contains the audience-oriented tutorials above.

## Features

None of the following features are enabled by default, so you can pick and choose which parts of the library you want to use by enabling the corresponding features. Note that some features depend on each other, so enabling one feature might automatically enable other features as well. For example, enabling `up-core-api` will also enable `protobuf-support` since the generated types require that.

* `cloudevents` Enables support for mapping [crate::UMessage]s to/from [crate::CloudEvent]s using Protobuf Format according to the
  [uProtocol specification](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l1/cloudevents.adoc).
* `communication` Enables default implementations for all [Communication Layer API](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l2/api.adoc) traits on top of the [Transport & Session Layer API](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l1/README.adoc).
* `protobuf-support` Enables convenience functions on the Transport & Session as well as the Communcation Layer APIs for implicitly mapping objects to protobuf payloads on the fly. This is particularly useful for using protoc-generated types as payloads using the [message builder](crate::UMessageBuilder::build_with_protobuf_payload) or [payload constructor](crate::communication::UPayload::try_from_protobuf). The only requirement for the object types is that they implement the [crate::ProtobufMappable] trait. A blanket implementation for types generated by the `protobuf` crate is also provided. Note that it is still possible to use protobufs as payloads even without enabling this feature. The payload of a [crate::UMessage] can be set to an arbitrary byte array, so protobuf messages can be serialized to bytes and set as payload without any support from the library. Enabling this feature just adds some convenient helper functions for automatically handling the mapping to protobuf payloads. The examples also illustrate the usage of these helper functions.
* `symphony` Enables support for implementing an [Eclipse Symphony](https://github.com/eclipse-symphony) Target Provider as a uService exposed via the Communication Layer API's [RPC Server](crate::communication::RpcServer).
* `test-util` provides some useful mock implementations for testing. In particular, provides mock implementations of [UTransport] and Communication Layer API traits which make implementing unit tests a lot easier.
* `up-core-api` Enables support for mapping the crate's public API types to protobufs as defined in the uProtocol specification. This includes, for example, the `UStatus` type which is used in the Communication Layer API for conveying errors. Enabling this feature also enables `protobuf-support` since the generated types require that.
* `communication-api` Enables support for the [Communication Layer API](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l2/api.adoc). This includes the trait definitions for the various roles defined by the API, such as [Notifier](crate::communication::Notifier), [Publisher](crate::communication::Publisher), [Subscriber](crate::communication::Subscriber), [RpcClient](crate::communication::RpcClient) and [RpcServer](crate::communication::RpcServer).
* `up-l2-notifier` Enables a default implementation of the [Notifier](crate::communication::Notifier) trait on top of the Transport Layer API.
* `up-l2-publisher` Enables a default implementation of the [Publisher](crate::communication::Publisher) trait on top of the Transport Layer API.
* `up-l2-subscriber` Enables a default implementation of the [Subscriber](crate::communication::Subscriber) trait on top of the Transport Layer API.
* `up-l2-rpc-client` Enables a default implementation of the [RpcClient](crate::communication::RpcClient) trait on top of the Transport Layer API.
* `up-l2-rpc-server` Enables a default implementation of the [RpcServer](crate::communication::RpcServer) trait on top of the Transport Layer API.
* `udiscovery` Enables support for types required to interact with [uDiscovery service](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l3/udiscovery/v3/README.adoc)
  implementations.
* `usubscription` Enables support for types required to interact with [uSubscription service](https://github.com/eclipse-uprotocol/up-spec/blob/v1.6.0-alpha.7/up-l3/usubscription/v3/README.adoc)
  implementations.
* `util` provides some useful helper structs. In particular, provides a [local, in-memory UTransport](crate::local_transport::LocalTransport) for exchanging messages within a single process. This transport is also used by the examples illustrating usage of the Communication Layer API.

## References

* [uProtocol Specification](https://github.com/eclipse-uprotocol/up-spec/tree/v1.6.0-alpha.7)

*/

#[cfg(feature = "cloudevents")]
mod cloudevents;
#[cfg(feature = "cloudevents")]
pub use cloudevents::{CloudEvent, CONTENT_TYPE_CLOUDEVENTS_PROTOBUF};

// [impl->dsn~communication-layer-api-namespace~1]
#[cfg(feature = "communication-api")]
pub mod communication;

#[cfg(any(feature = "udiscovery", feature = "usubscription"))]
pub mod core;

#[cfg(feature = "util")]
pub mod local_transport;

/// A guided tour of the crate: start here if the reference docs feel
/// like a parts list. Chapter by chapter, with runnable examples.
pub mod guide {
    #![doc = include_str!("guide/README.md")]

    #[cfg_attr(
        all(feature = "communication", feature = "util"),
        doc = include_str!("guide/applications.md")
    )]
    #[cfg_attr(
        not(all(feature = "communication", feature = "util")),
        doc = "Enable `communication` and `util` for the runnable application guide."
    )]
    pub mod applications {
        #[cfg_attr(
            all(feature = "communication", feature = "util"),
            doc = include_str!("guide/communication.md")
        )]
        #[cfg_attr(
            not(all(feature = "communication", feature = "util")),
            doc = "Enable `communication` and `util` for the runnable Communication Layer guide."
        )]
        pub mod communication {}

        #[doc = include_str!("guide/transport.md")]
        pub mod transport {}
    }

    #[cfg_attr(feature = "util", doc = include_str!("guide/utransport.md"))]
    #[cfg_attr(
        not(feature = "util"),
        doc = "Enable `util` for the runnable transport implementation guide."
    )]
    pub mod utransport {}

    #[doc = include_str!("guide/trait_map.md")]
    pub mod trait_map {}
}

#[cfg(feature = "symphony")]
pub mod symphony;

mod uattributes;
pub use uattributes::{
    NotificationValidator, PayloadEncoding, PublishValidator, RequestValidator, ResponseValidator,
    UAttributes, UAttributesError, UAttributesValidator, UAttributesValidators, UMessageType,
    UPriority, PAYLOAD_ENCODING_PRIVATE_USE_MIN,
};

mod umessage;
pub use umessage::{
    BuilderState, NotificationBuilderState, PublishBuilderState, RequestBuilderState,
    ResponseBuilderState, UMessage, UMessageBuilder, UMessageError,
};

mod uri;
pub use uri::{ExactUUri, UUri, UUriError};

mod ustatus;
pub use ustatus::{UAny, UCode, UStatus};

mod utransport;
pub use utransport::{
    verify_filter_criteria, ComparableListener, LocalUriProvider, StaticUriProvider, UListener,
    UTransport,
};
#[cfg(feature = "test-util")]
pub use utransport::{MockLocalUriProvider, MockTransport, MockUListener};

mod uuid;
pub use uuid::UUID;

#[cfg(feature = "up-core-api")]
// protoc-generated types, see build.rs
pub(crate) mod up_core_api {
    include!(concat!(env!("OUT_DIR"), "/uprotocol/mod.rs"));
}

#[cfg(feature = "protobuf-support")]
mod protobuf_mappable;
#[cfg(feature = "protobuf-support")]
pub use protobuf_mappable::ProtobufMappable;

mod serialization_error;
pub use serialization_error::SerializationError;

// ---- native frame model ----

mod validation_state;
pub use validation_state::{Unvalidated, Validated};

/// The native frame data model: metadata, canonical field-block codec, and
/// the read-side frame view contract.
pub mod frame;
pub use frame::metadata::{FrameMessageKind, FramePriority, UFrameMetadata, UFrameMetadataError};
pub use frame::{validate_frame_view_for_transport, UFrameView};

/// Payload codec contracts shared by the frame families.
pub mod payload;
pub use payload::codec::{
    DecodePayload, EncodePayload, PayloadCodec, PayloadCodecIdentity, PayloadLayout,
    ProtobufPayload, ReadDecodePayload,
};
pub use payload::UWireError;

// ---- wire formats ----

#[cfg(feature = "wire-implementer-api")]
pub mod wire;
#[cfg(not(feature = "wire-implementer-api"))]
mod wire;
#[cfg(any(feature = "selected-wire-user-api", feature = "wire-implementer-api"))]
pub use wire::NativePrefixFrameMetadataCodec;
#[cfg(any(feature = "selected-wire-user-api", feature = "wire-implementer-api"))]
pub use wire::{
    ProtobufWire, UProtocolNativeWire, WireCompatibility, WireIdentity, WireIdentityRef,
    NATIVE_EXPLICIT_PAYLOAD_FAMILY_ID, NATIVE_PREFIX_METADATA_LAYOUT_ID,
    PROTOBUF_PAYLOAD_FAMILY_ID, PROTOBUF_WIRE_ID, UFRAME_FIELDS_METADATA_LAYOUT_ID,
    UPROTOCOL_NATIVE_WIRE_ID, XCDR_V2_PAYLOAD_FAMILY_ID, XCDR_V2_WIRE_ID,
};
#[cfg(feature = "wire-implementer-api")]
pub use wire::{
    UWire, UWireDecode, UWireEncode, UWireMetadataCodec, UWireMetadataCodecFor,
    UWireMetadataContext, UWireMetadataError, UWirePayload, UWireReadDecode,
};

/// Compatibility import surface for wire-format implementers.
///
/// The crate root remains canonical; this role-oriented module groups the same
/// public contracts for existing wire crates and focused imports.
#[cfg(feature = "wire-implementer-api")]
pub mod wire_implementer_api {
    pub use crate::{
        NativePrefixFrameMetadataCodec, ProtobufWire, UProtocolNativeWire, UWire, UWireDecode,
        UWireEncode, UWireMetadataCodec, UWireMetadataCodecFor, UWireMetadataContext,
        UWireMetadataError, UWirePayload, UWireReadDecode, WireCompatibility, WireIdentity,
        WireIdentityRef, NATIVE_EXPLICIT_PAYLOAD_FAMILY_ID, NATIVE_PREFIX_METADATA_LAYOUT_ID,
        PROTOBUF_PAYLOAD_FAMILY_ID, PROTOBUF_WIRE_ID, UFRAME_FIELDS_METADATA_LAYOUT_ID,
        UPROTOCOL_NATIVE_WIRE_ID, XCDR_V2_PAYLOAD_FAMILY_ID, XCDR_V2_WIRE_ID,
    };
}
